events {}

http {
	server {
		listen 80;
		server_name _;

		root /var/www;

		location /static/ {
			include /etc/nginx/mime.types;
			try_files $uri =404;
		}

		location /templates/ {
			include /etc/nginx/mime.types;
			try_files $uri =404;
		}

		location / {
			try_files $uri $uri/ /index.html;
		}
	}
}
